CREATE TABLE IF NOT EXISTS books
(
    book_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    author      VARCHAR(30)  NOT NULL,
    price       DECIMAL,
    isPresent   BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS customers
(
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(35) NOT NULL,
    surname     VARCHAR(50) NOT NULL,
    email       VARCHAR(50) NOT NULL,
    phone       VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    books       BIGINT[] NOT NULL,
    createdDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    sum         decimal
);

SELECT book_id, title, author, price, createdDate FROM
                books b LEFT JOIN orders o ON b.book_id = ANY (o.books)
                WHERE createdDate = '2025-01-20 00:00:00.000000'