CREATE TABLE IF NOT EXISTS books
(
    book_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    author      VARCHAR(30)  NOT NULL,
    price       DECIMAL,
    isPresent   BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS customers
(
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(35) NOT NULL,
    surname     VARCHAR(50) NOT NULL,
    email       VARCHAR(50) NOT NULL,
    phone       VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    createdDate TIMESTAMP WITH TIME ZONE NOT NULL,
    sum         decimal
);

CREATE TABLE IF NOT EXISTS order_books
(
    order_id INT NOT NULL,
    book_id  INT NOT NULL,
    CONSTRAINT PK_ORDER_BOOKS
        PRIMARY KEY (order_id, book_id),
    CONSTRAINT FK_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT FK_BOOK FOREIGN KEY (book_id) REFERENCES books (book_id) ON DELETE CASCADE
);
